export const OPEN_CREATE_POST_MODAL_ASYNC = 'OPEN_CREATE_POST_MODAL_ASYNC'
export const CLOSE_CREATE_POST_MODAL_ASYNC = 'CLOSE_CREATE_POST_MODAL_ASYNC'
export const FAIL_SAVE_CREATE_POST_ASYNC = 'FAIL_SAVE_CREATE_POST_ASYNC'