export const VERIFY_IF_ALREDY_LOGGED_ASYNC = 'VERIFY_IF_ALREDY_LOGGED_ASYNC'
export const LOGIN_PROCCESS_ASYNC = 'LOGIN_PROCCESS_ASYNC'
export const LOGIN_FAIL_ASYNC = 'LOGIN_FAIL_ASYNC'
export const LOGOUT_ASYNC = 'LOGOUT_ASYNC'
